apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argooperatorrole
  namespace: argo
rules:
  # k8s standard APIs
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  # Argo APIs. 
  - apiGroups:
      - argoproj.io
    resources:
      - "*"
    verbs:
      - get
      - patch
      - create 
      - list
      - watch
      - delete
  # k8s standard APIs
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watcharg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argooperatorrolebinding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argooperator
  namespace: argo
roleRef:
  kind: Role
  name: argooperatorrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argooperator
  namespace: argo
secrets:
- name: argooperator-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: argooperator-sa
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argooperator
type: kubernetes.io/service-account-token
